"""Traductor de FDS (Fichas de Datos de Seguridad) de español a inglés.

Traduce las 16 secciones estándar GHS/SGA al formato SDS (Safety Data Sheet).
"""

# Mapping of Spanish section titles to English equivalents
TITULOS_EN = {
    "1": "SECTION 1: Identification of the substance/mixture and of the company/undertaking",
    "2": "SECTION 2: Hazards identification",
    "3": "SECTION 3: Composition/information on ingredients",
    "4": "SECTION 4: First-aid measures",
    "5": "SECTION 5: Firefighting measures",
    "6": "SECTION 6: Accidental release measures",
    "7": "SECTION 7: Handling and storage",
    "8": "SECTION 8: Exposure controls/personal protection",
    "9": "SECTION 9: Physical and chemical properties",
    "10": "SECTION 10: Stability and reactivity",
    "11": "SECTION 11: Toxicological information",
    "12": "SECTION 12: Ecological information",
    "13": "SECTION 13: Disposal considerations",
    "14": "SECTION 14: Transport information",
    "15": "SECTION 15: Regulatory information",
    "16": "SECTION 16: Other information",
}

# Spanish → English phrase translations for FDS content
_TRADUCCIONES = [
    # Section 1
    ("1.1 Identificador del producto", "1.1 Product identifier"),
    ("Nombre del producto:", "Product name:"),
    ("Lote:", "Batch:"),
    ("Fecha de elaboracion:", "Date of preparation:"),
    ("Tipo: Mezcla", "Type: Mixture"),
    ("1.2 Usos pertinentes identificados", "1.2 Relevant identified uses"),
    ("Uso: Producto cosmetico / de aseo / industrial (segun formulacion)",
     "Use: Cosmetic / cleaning / industrial product (according to formulation)"),
    ("1.3 Datos del proveedor de la ficha de datos de seguridad",
     "1.3 Details of the supplier of the safety data sheet"),
    ("Empresa:", "Company:"),
    ("Direccion:", "Address:"),
    ("Telefono:", "Phone:"),
    ("Email:", "Email:"),
    ("1.4 Telefono de emergencia", "1.4 Emergency telephone number"),

    # Section 2
    ("2.1 Clasificacion de la sustancia o de la mezcla",
     "2.1 Classification of the substance or mixture"),
    ("Clasificacion segun el SGA/GHS:", "Classification according to GHS:"),
    ("No clasificado como peligroso.", "Not classified as hazardous."),
    ("2.2 Elementos de la etiqueta", "2.2 Label elements"),
    ("Pictogramas:", "Pictograms:"),
    ("Palabra de advertencia:", "Signal word:"),
    ("Sin palabra de advertencia", "No signal word"),
    ("Indicaciones de peligro (H):", "Hazard statements (H):"),
    ("2.3 Otros peligros", "2.3 Other hazards"),
    ("No se conocen otros peligros adicionales.", "No other hazards are known."),

    # Section 3
    ("Componentes:", "Components:"),
    ("No especificados.", "Not specified."),

    # Section 4
    ("4.1 Descripcion de los primeros auxilios", "4.1 Description of first-aid measures"),
    ("En caso de ingestion:", "If swallowed:"),
    ("NO provocar el vomito.", "Do NOT induce vomiting."),
    ("Enjuagar la boca con agua.", "Rinse mouth with water."),
    ("Llamar inmediatamente a un centro de informacion toxicologica o a un medico.",
     "Call a POISON CENTER or doctor immediately."),
    ("Llamar a un centro de informacion toxicologica o a un medico si se siente mal.",
     "Call a POISON CENTER or doctor if you feel unwell."),
    ("Enjuagar la boca con agua. Consultar a un medico si aparecen sintomas.",
     "Rinse mouth with water. Get medical advice if symptoms occur."),
    ("En caso de contacto con la piel:", "If on skin:"),
    ("Quitar inmediatamente la ropa contaminada.",
     "Immediately take off contaminated clothing."),
    ("Lavar con abundante agua durante al menos 15 minutos.",
     "Wash with plenty of water for at least 15 minutes."),
    ("Llamar a un medico inmediatamente.", "Call a doctor immediately."),
    ("Quitar la ropa contaminada.", "Take off contaminated clothing."),
    ("Lavar con abundante agua y jabon.", "Wash with plenty of water and soap."),
    ("Llamar a un centro de informacion toxicologica.",
     "Call a POISON CENTER."),
    ("Si persiste la irritacion, consultar a un medico.",
     "If irritation persists, get medical advice."),
    ("Lavar con agua y jabon. Consultar a un medico si aparecen sintomas.",
     "Wash with water and soap. Get medical advice if symptoms occur."),
    ("En caso de contacto con los ojos:", "If in eyes:"),
    ("Lavar los ojos con agua limpia durante al menos 15 minutos.",
     "Rinse eyes with clean water for at least 15 minutes."),
    ("Quitar las lentes de contacto si es posible.",
     "Remove contact lenses if easy to do."),
    ("Consultar a un oftalmologo inmediatamente.",
     "Immediately consult an ophthalmologist."),
    ("Aclarar los ojos con agua durante varios minutos.",
     "Rinse eyes with water for several minutes."),
    ("Si persiste la irritacion, consultar a un medico.",
     "If irritation persists, get medical advice."),
    ("Aclarar los ojos con agua durante varios minutos. Consultar a un medico si hay molestias.",
     "Rinse eyes with water for several minutes. Get medical advice if discomfort persists."),
    ("En caso de inhalacion:", "If inhaled:"),
    ("Transportar a la victima al aire fresco.", "Move victim to fresh air."),
    ("Mantener en reposo.", "Keep at rest."),
    ("Si no respira, administrar respiracion artificial con proteccion respiratoria.",
     "If not breathing, give artificial respiration with respiratory protection."),
    ("Transportar al aire fresco.", "Move to fresh air."),
    ("En caso de dificultad respiratoria, consultar a un medico.",
     "If breathing is difficult, get medical advice."),
    ("Transportar al aire fresco si hay sintomas. Consultar a un medico si persisten las molestias.",
     "Move to fresh air if symptoms occur. Get medical advice if discomfort persists."),
    ("4.2 Principales sintomas y efectos",
     "4.2 Most important symptoms and effects"),
    ("Los sintomas dependen de la via y duracion de la exposicion. Consultar la Seccion 11.",
     "Symptoms depend on route and duration of exposure. See Section 11."),
    ("4.3 Indicacion de toda atencion medica y de los tratamientos especiales que deban dispensarse",
     "4.3 Indication of immediate medical attention and special treatment needed"),
    ("Tratamiento sintomatico. No se conoce antidoto especifico.",
     "Symptomatic treatment. No specific antidote is known."),

    # Section 5
    ("5.1 Medios de extincion", "5.1 Extinguishing media"),
    ("Medios de extincion apropiados: Espuma resistente al alcohol, CO2, polvo seco, agua pulverizada.",
     "Suitable extinguishing media: Alcohol-resistant foam, CO2, dry powder, water spray."),
    ("Medios de extincion no apropiados: Chorro directo de agua (puede propagar el producto).",
     "Unsuitable extinguishing media: Direct water jet (may spread the product)."),
    ("5.2 Peligros especificos derivados de la sustancia o la mezcla",
     "5.2 Special hazards arising from the substance or mixture"),
    ("Producto inflamable. Vapores pueden formar mezclas explosivas con el aire.",
     "Flammable product. Vapors may form explosive mixtures with air."),
    ("No se esperan peligros especiales de incendio.",
     "No special fire hazards are expected."),
    ("5.3 Recomendaciones para el personal de lucha contra incendios",
     "5.3 Advice for firefighters"),
    ("Utilizar equipo de respiracion autonomo y traje de proteccion completo.",
     "Use self-contained breathing apparatus and full protective clothing."),

    # Section 6
    ("6.1 Precauciones personales, equipos de proteccion y procedimientos de emergencia",
     "6.1 Personal precautions, protective equipment and emergency procedures"),
    ("Utilizar equipo de proteccion individual (ver Seccion 8).",
     "Use personal protective equipment (see Section 8)."),
    ("Evacuar el area si es necesario. Ventilar la zona.",
     "Evacuate area if necessary. Ventilate the area."),
    ("6.2 Precauciones relativas al medio ambiente",
     "6.2 Environmental precautions"),
    ("Evitar que el producto entre en desagues, cursos de agua o el suelo. Producto toxico para organismos acuaticos.",
     "Prevent product from entering drains, watercourses or soil. Product is toxic to aquatic organisms."),
    ("Evitar que el producto entre en desagues o cursos de agua.",
     "Prevent product from entering drains or watercourses."),
    ("6.3 Metodos y material de contencion y de limpieza",
     "6.3 Methods and material for containment and cleaning up"),
    ("Absorber con material inerte (arena, tierra, vermiculita).",
     "Absorb with inert material (sand, earth, vermiculite)."),
    ("Recoger en recipientes adecuados para su eliminacion.",
     "Collect in suitable containers for disposal."),

    # Section 7
    ("7.1 Precauciones para una manipulacion segura",
     "7.1 Precautions for safe handling"),
    ("Mantener alejado de fuentes de calor, chispas, llama abierta y superficies calientes. No fumar.",
     "Keep away from heat, sparks, open flames and hot surfaces. No smoking."),
    ("Eliminar fuentes de ignicion. Tomar medidas contra descargas electrostaticas.",
     "Remove ignition sources. Take measures against electrostatic discharges."),
    ("Evitar formacion de polvo. Mantener alejado de fuentes de ignicion.",
     "Avoid dust formation. Keep away from ignition sources."),
    ("Evitar contacto con agua.", "Avoid contact with water."),
    ("Mantener alejado de materiales combustibles.",
     "Keep away from combustible materials."),
    ("Proteger de la luz solar. No exponer a temperaturas superiores a 50 C.",
     "Protect from sunlight. Do not expose to temperatures exceeding 50°C."),
    ("Utilizar equipo de proteccion individual (ver Seccion 8). Evitar el contacto con los ojos, la piel y la ropa.",
     "Use personal protective equipment (see Section 8). Avoid contact with eyes, skin and clothing."),
    ("7.2 Condiciones de almacenamiento seguro",
     "7.2 Conditions for safe storage"),
    ("Almacenar en un lugar fresco y bien ventilado. Mantener el recipiente cerrado hermeticamente. Almacenar lejos de productos incompatibles (ver Seccion 10).",
     "Store in a cool, well-ventilated place. Keep container tightly closed. Store away from incompatible products (see Section 10)."),
    ("Guardar bajo llave.", "Store locked up."),
    ("7.3 Usos especificos finales", "7.3 Specific end use(s)"),
    ("Consultar la ficha tecnica del producto para usos especificos.",
     "Consult the product technical data sheet for specific uses."),

    # Section 8
    ("8.1 Parametros de control", "8.1 Control parameters"),
    ("Consultar los limites de exposicion profesional nacionales aplicables.",
     "Consult applicable national occupational exposure limits."),
    ("8.2 Controles de la exposicion", "8.2 Exposure controls"),
    ("Proteccion respiratoria: Utilizar mascara con filtro adecuado (tipo A para vapores organicos o P3 para particulas segun corresponda). En caso de concentraciones elevadas, equipo de respiracion autonomo.",
     "Respiratory protection: Use appropriate filter mask (type A for organic vapors or P3 for particles as appropriate). In case of high concentrations, use self-contained breathing apparatus."),
    ("Proteccion respiratoria: Utilizar en areas bien ventiladas. Si la ventilacion es insuficiente, utilizar mascara con filtro.",
     "Respiratory protection: Use in well-ventilated areas. If ventilation is insufficient, use filter mask."),
    ("Proteccion respiratoria: Normalmente no es necesaria si hay ventilacion adecuada.",
     "Respiratory protection: Normally not required with adequate ventilation."),
    ("Proteccion de las manos: Guantes resistentes a productos quimicos (nitrilo, neopreno o equivalente). Tiempo de penetracion > 480 min.",
     "Hand protection: Chemical-resistant gloves (nitrile, neoprene or equivalent). Breakthrough time > 480 min."),
    ("Proteccion de las manos: Guantes de proteccion quimica (nitrilo o equivalente).",
     "Hand protection: Chemical protection gloves (nitrile or equivalent)."),
    ("Proteccion de las manos: Guantes de proteccion adecuados al producto.",
     "Hand protection: Protective gloves suitable for the product."),
    ("Proteccion de los ojos: Gafas de seguridad hermeticas o pantalla facial.",
     "Eye protection: Tight-fitting safety goggles or face shield."),
    ("Proteccion de los ojos: Gafas de seguridad.",
     "Eye protection: Safety goggles."),
    ("Proteccion de los ojos: Gafas de proteccion si hay riesgo de salpicaduras.",
     "Eye protection: Safety goggles if there is a risk of splashing."),
    ("Proteccion cutanea: Ropa de proteccion adecuada. Delantal si hay riesgo de salpicaduras.",
     "Skin protection: Suitable protective clothing. Apron if there is risk of splashing."),

    # Section 9
    ("Aspecto:", "Appearance:"),
    ("Color:", "Color:"),
    ("Olor:", "Odor:"),
    ("pH:", "pH:"),
    ("Punto de fusion/congelacion:", "Melting/freezing point:"),
    ("Punto de ebullicion:", "Boiling point:"),
    ("Punto de inflamacion:", "Flash point:"),
    ("Velocidad de evaporacion:", "Evaporation rate:"),
    ("Inflamabilidad (solido, gas):", "Flammability (solid, gas):"),
    ("Presion de vapor:", "Vapor pressure:"),
    ("Densidad de vapor:", "Vapor density:"),
    ("Densidad relativa:", "Relative density:"),
    ("Solubilidad:", "Solubility:"),
    ("Viscosidad:", "Viscosity:"),
    ("No disponible", "Not available"),
    ("No determinado", "Not determined"),

    # Section 10
    ("10.1 Reactividad", "10.1 Reactivity"),
    ("No se dispone de datos especificos de reactividad.",
     "No specific reactivity data available."),
    ("10.2 Estabilidad quimica", "10.2 Chemical stability"),
    ("Estable en condiciones normales de almacenamiento y manipulacion.",
     "Stable under normal storage and handling conditions."),
    ("10.3 Posibilidad de reacciones peligrosas",
     "10.3 Possibility of hazardous reactions"),
    ("Puede reaccionar con oxidantes fuertes.",
     "May react with strong oxidizers."),
    ("No se esperan reacciones peligrosas en condiciones normales.",
     "No hazardous reactions expected under normal conditions."),
    ("10.4 Condiciones que deben evitarse", "10.4 Conditions to avoid"),
    ("Calor, llamas, chispas. Evitar fuentes de ignicion.",
     "Heat, flames, sparks. Avoid ignition sources."),
    ("Calor excesivo, luz solar directa.", "Excessive heat, direct sunlight."),
    ("10.5 Materiales incompatibles", "10.5 Incompatible materials"),
    ("Agentes oxidantes fuertes, acidos fuertes, bases fuertes.",
     "Strong oxidizing agents, strong acids, strong bases."),
    ("10.6 Productos de descomposicion peligrosos",
     "10.6 Hazardous decomposition products"),
    ("En caso de incendio puede generar CO, CO2 y humos toxicos.",
     "In case of fire, may generate CO, CO2 and toxic fumes."),

    # Section 11
    ("11.1 Informacion sobre los efectos toxicologicos",
     "11.1 Information on toxicological effects"),
    ("Toxicidad aguda:", "Acute toxicity:"),
    ("No clasificado para toxicidad aguda basado en los datos disponibles.",
     "Not classified for acute toxicity based on available data."),
    ("Corrosion cutanea: Provoca quemaduras graves en la piel.",
     "Skin corrosion: Causes severe skin burns."),
    ("Irritacion cutanea: Provoca irritacion cutanea.",
     "Skin irritation: Causes skin irritation."),
    ("Lesion ocular grave: Provoca lesiones oculares graves.",
     "Serious eye damage: Causes serious eye damage."),
    ("Irritacion ocular: Provoca irritacion ocular grave.",
     "Eye irritation: Causes serious eye irritation."),
    ("Sensibilizacion respiratoria: Puede provocar sintomas de alergia o asma.",
     "Respiratory sensitization: May cause allergy or asthma symptoms."),
    ("Sensibilizacion cutanea: Puede provocar una reaccion alergica en la piel.",
     "Skin sensitization: May cause an allergic skin reaction."),
    ("Mutagenicidad: Puede provocar defectos geneticos (mutageno categoria 1).",
     "Mutagenicity: May cause genetic defects (mutagen category 1)."),
    ("Mutagenicidad: Se sospecha que provoca defectos geneticos (mutageno categoria 2).",
     "Mutagenicity: Suspected of causing genetic defects (mutagen category 2)."),
    ("Carcinogenicidad: Puede provocar cancer (cancerigeno categoria 1).",
     "Carcinogenicity: May cause cancer (carcinogen category 1)."),
    ("Carcinogenicidad: Se sospecha que provoca cancer (cancerigeno categoria 2).",
     "Carcinogenicity: Suspected of causing cancer (carcinogen category 2)."),
    ("Toxicidad para la reproduccion: Puede perjudicar la fertilidad o al feto.",
     "Reproductive toxicity: May damage fertility or the unborn child."),
    ("Toxicidad para la reproduccion: Se sospecha que perjudica la fertilidad o al feto.",
     "Reproductive toxicity: Suspected of damaging fertility or the unborn child."),
    ("Toxicidad especifica en determinados organos (exposicion unica): Provoca danos en los organos (organo diana especificado).",
     "Specific target organ toxicity (single exposure): Causes damage to organs (target organ specified)."),
    ("Toxicidad especifica en determinados organos (exposicion repetida): Provoca danos en los organos tras exposiciones prolongadas o repetidas.",
     "Specific target organ toxicity (repeated exposure): Causes damage to organs through prolonged or repeated exposure."),

    # Section 12
    ("12.1 Toxicidad", "12.1 Toxicity"),
    ("Toxicidad acuatica aguda: Muy toxico para los organismos acuaticos (Categoria 1).",
     "Acute aquatic toxicity: Very toxic to aquatic life (Category 1)."),
    ("Toxicidad acuatica cronica: Muy toxico para los organismos acuaticos con efectos nocivos duraderos (Categoria 1).",
     "Chronic aquatic toxicity: Very toxic to aquatic life with long lasting effects (Category 1)."),
    ("Toxicidad acuatica cronica: Toxico para los organismos acuaticos con efectos nocivos duraderos (Categoria 2).",
     "Chronic aquatic toxicity: Toxic to aquatic life with long lasting effects (Category 2)."),
    ("Nocivo para los organismos acuaticos con efectos nocivos duraderos (Categoria 3).",
     "Harmful to aquatic life with long lasting effects (Category 3)."),
    ("No se clasifica como peligroso para el medio acuatico basado en los datos disponibles.",
     "Not classified as hazardous to the aquatic environment based on available data."),
    ("12.2 Persistencia y degradabilidad", "12.2 Persistence and degradability"),
    ("No se dispone de datos especificos.", "No specific data available."),
    ("12.3 Potencial de bioacumulacion", "12.3 Bioaccumulative potential"),
    ("12.4 Movilidad en el suelo", "12.4 Mobility in soil"),
    ("12.5 Resultados de la valoracion PBT y mPmB",
     "12.5 Results of PBT and vPvB assessment"),
    ("No se ha realizado esta valoracion.", "This assessment has not been performed."),
    ("12.6 Otros efectos adversos", "12.6 Other adverse effects"),
    ("Peligroso para la capa de ozono.", "Hazardous to the ozone layer."),

    # Section 13
    ("13.1 Metodos para el tratamiento de residuos",
     "13.1 Waste treatment methods"),
    ("Producto clasificado como residuo peligroso.",
     "Product classified as hazardous waste."),
    ("Eliminar de acuerdo con la normativa local y nacional vigente.",
     "Dispose of in accordance with local and national regulations."),
    ("No verter en desagues ni cursos de agua.",
     "Do not discharge into drains or watercourses."),
    ("Entregar a un gestor autorizado de residuos.",
     "Hand over to an authorized waste disposal company."),
    ("13.2 Envases", "13.2 Packaging"),
    ("Los envases contaminados deben tratarse como el propio residuo.",
     "Contaminated packaging should be treated as the waste itself."),

    # Section 14
    ("14.1 Numero ONU: No asignado (verificar segun clasificacion final)",
     "14.1 UN number: Not assigned (verify according to final classification)"),
    ("14.2 Designacion oficial de transporte:", "14.2 UN proper shipping name:"),
    ("14.3 Clase(s) de peligro para el transporte: Consultar normativa local",
     "14.3 Transport hazard class(es): Consult local regulations"),
    ("14.4 Grupo de embalaje: Consultar normativa local",
     "14.4 Packing group: Consult local regulations"),
    ("14.5 Peligros para el medio ambiente:", "14.5 Environmental hazards:"),
    ("Si - Contaminante marino", "Yes - Marine pollutant"),
    ("No determinado", "Not determined"),
    ("14.6 Precauciones particulares: Seguir las normativas de transporte vigentes.",
     "14.6 Special precautions: Follow current transport regulations."),

    # Section 15
    ("15.1 Normativa y legislacion en materia de seguridad, salud y medio ambiente",
     "15.1 Safety, health and environmental regulations/legislation"),
    ("- Sistema Globalmente Armonizado (SGA/GHS) Rev. 9",
     "- Globally Harmonized System (GHS) Rev. 9"),
    ("- Regulacion local aplicable segun jurisdiccion",
     "- Applicable local regulations per jurisdiction"),
    ("- Normativa cosmetica aplicable (si corresponde)",
     "- Applicable cosmetic regulations (if applicable)"),
    ("15.2 Evaluacion de la seguridad quimica",
     "15.2 Chemical safety assessment"),
    ("No se ha realizado una evaluacion de la seguridad quimica para esta mezcla.",
     "A chemical safety assessment has not been performed for this mixture."),

    # Section 16
    ("Fecha de elaboracion de la FDS:", "Date of preparation of the SDS:"),
    ("Version:", "Version:"),
    ("Abreviaturas:", "Abbreviations:"),
    ("- SGA/GHS: Sistema Globalmente Armonizado de clasificacion y etiquetado de productos quimicos",
     "- GHS: Globally Harmonized System of Classification and Labelling of Chemicals"),
    ("- FDS: Ficha de Datos de Seguridad", "- SDS: Safety Data Sheet"),
    ("- CAS: Chemical Abstracts Service", "- CAS: Chemical Abstracts Service"),
    ("- INCI: Nomenclatura Internacional de Ingredientes Cosmeticos",
     "- INCI: International Nomenclature of Cosmetic Ingredients"),
    ("- ATE: Estimacion de Toxicidad Aguda", "- ATE: Acute Toxicity Estimate"),
    ("- EPI: Equipo de Proteccion Individual", "- PPE: Personal Protective Equipment"),
    ("Esta FDS ha sido generada por el Sistema FSD 2026.",
     "This SDS has been generated by the FSD 2026 System."),
    ("La informacion contenida se basa en los datos disponibles a la fecha de elaboracion y no constituye garantia de las propiedades del producto.",
     "The information contained herein is based on data available at the date of preparation and does not constitute a guarantee of the product's properties."),

    # Common terms
    ("Ninguno", "None"),
    ("Peligro", "Danger"),
    ("Atencion", "Warning"),
    ("c.s.p.", "q.s. (quantum satis)"),
    ("Categoria", "Category"),
]


def traducir_fds(secciones_es):
    """Traduce un dict de secciones FDS del español al inglés.

    Args:
        secciones_es: dict con claves "1"-"16", cada una con "titulo" y "contenido"

    Returns:
        dict con la misma estructura pero títulos y contenidos traducidos al inglés
    """
    secciones_en = {}
    for num, sec in secciones_es.items():
        titulo_en = TITULOS_EN.get(str(num), sec.get("titulo", f"Section {num}"))
        contenido = sec.get("contenido", "")
        contenido_en = _traducir_contenido(contenido)
        secciones_en[num] = {
            "titulo": titulo_en,
            "contenido": contenido_en,
        }
    return secciones_en


def _traducir_contenido(texto):
    """Aplica traducciones línea por línea y frase por frase."""
    resultado = texto
    # Sort by length descending so longer phrases match first
    for es, en in sorted(_TRADUCCIONES, key=lambda x: len(x[0]), reverse=True):
        resultado = resultado.replace(es, en)
    return resultado
